name: feelps
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  
  flutter:
    sdk: flutter

  flutter_mobx: ^2.0.0
  flutter_modular: ^3.2.2+1
  flutter_multi_formatter: ^2.2.0
  flutter_secure_storage: ^4.2.0
  flutter_svg: ^0.22.0
  lint: ^1.5.3
  mobx: ^2.0.1

dev_dependencies:
  build_runner: ^2.0.4
  change_app_package_name: ^1.0.0
  firebase_auth_mocks: ^0.6.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1+3
  mocktail: ^0.1.4
  modular_codegen: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/illustrations/
    - assets/images/