name: feelps
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  asuka: ^2.0.0-nullsafety.2
  camera_camera: ^2.0.2
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.0
  equatable: ^2.0.3
  firebase_auth: ^1.4.1
  firebase_core: ^1.3.0
  firebase_database: ^7.1.1
  firebase_messaging: ^10.0.2
  firebase_storage: ^10.0.3
  flutter:
    sdk: flutter

  flutter_cupertino_datetime_picker: ^2.0.1
  flutter_masked_text2: ^0.9.1
  flutter_mobx: ^2.0.0
  flutter_modular: ^3.3.1
  flutter_multi_formatter: ^2.2.0
  flutter_secure_storage: ^4.2.0
  flutter_svg: ^0.22.0
  google_maps_flutter: ^2.0.6
  image: ^3.0.2
  image_picker: ^0.8.2
  lint: ^1.5.3
  location: ^4.3.0
  mobx: ^2.0.1
  path_provider: ^2.0.2
  string_validator: ^0.3.0

dev_dependencies:
  build_runner: ^2.0.4
  change_app_package_name: ^1.0.0
  firebase_auth_mocks: ^0.6.0
  firebase_database_mock: ^0.1.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1+3
  mocktail: ^0.1.4
  modular_codegen: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/illustrations/
    - assets/images/